image: python:3.11  # Utilise une image Docker avec Python 3.11

stages:
  - test  # Étape unique pour les tests

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"  # Utilise un cache pour les dépendances Python

before_script:
  - pip install --upgrade pip  # Met à jour pip
  - pip install hatch  # Installe Hatch pour gérer le projet

# test_job:
#   stage: test
#   script:
#     - hatch env create  # Crée l'environnement virtuel pour le projet avec Hatch
#     - hatch test    # Lance les tests unitaires
#   tags:
#    - docker
image: mcr.microsoft.com/windows/servercore:ltsc2022  # Exemple d'image Docker Windows

test-job:
  stage: test
  tags:
    - docker  # tag pour indiquer que ce job utilise Docker
  script:
    - set PYTHONPATH=%PYTHONPATH%;%cd%/src
    - pip install --upgrade pip
    - pip install hatch
    - pip install pytest pytest-cov
    - hatch test
    - pytest --cov=src.projet-gitlab-runner.gdc --cov-report=xml:coverage.xml --cov-report=term-missing
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  coverage: '/TOTAL.*? (\d+\%)$/'

  tags:
    - docker

