image: python:3.11  # Utilise une image Docker avec Python 3.11

stages:
  - test  # Étape unique pour les tests

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"  # Utilise un cache pour les dépendances Python

before_script:
  - pip install --upgrade pip  # Met à jour pip
  - pip install hatch  # Installe Hatch pour gérer le projet

test_job:
  stage: test
  script:
    - export PYTHONPATH=$PYTHONPATH:$(pwd)/src
    - apk add gcc python3-dev musl-dev linux-headers
    - pip install --upgrade pip
    - pip install hatch
    - pip install pytest pytest
    - cov
    - hatch test
    - pytest --cov=src.projet-gitlab-runner.gdc --cov-report=xml --cov-report=term-missing
artifacts:
  reports:
    coverage_report:
      coverage_format: cobertura
      path: coverage.xml 
coverage: '/TOTAL.*? (\d+%)$/'
tags: 
 - docker
